---
title: "Week 4: R as a form of GIS"
description: "CRS and a lot of geography"
date: 2026-09-18
title-block-banner: images/note-banner.jpg
title-block-banner-color: white
format: html
---

## Overview of Lecture

1.  Quick overview of last week's content
2.  R as a form of GIS (Vector Operations)

## 1. Recap of Content

Remember that the margin of error tells us the 90% confidence interval. This is the confidence interval selected by ACS5. It is baked in.

::: {.callout-tip collapse="false"}
Take note of this for your assignment. Let's say that you have ACS5 data sets from 2015 and 2023 with an MOE of +/- 3 and +/- 4 respectively. We are trying to figure out the uncertainty around the difference. This is where the Standard Error (SE) comes in.
:::

### Calculating the SE with the variables in the example

$$SE_{diff} = \sqrt{({\frac{3}{1.645})}^2 + ({\frac{4}{1.645}})^2} = 3.04$$ $$ Z_{score} = \frac{25-20}{3.04} \approx 1.64 \le 1.65 $$ As such, the noise is significant and we should slow down to think about the data more. It is unlikely to be due to sampling noise.

## 2. Using R for Spatial GIS

### Joining Tables

#### Example

| GEOID | med.inc.23 |
|-------|------------|
| 100   | 82000      |
| 200   | 31500      |
| 300   | 45000      |

| GEOID | med.inc.15 |
|-------|------------|
| 100   | 61000      |
| 200   | 27000      |
| 400   | 39000      |

```{left_join(income.b, income.c, by="GEOID")}
```

#### Output

| GEOID | med.inc.23 | med.inc.15 |
|-------|------------|------------|
| 100   | 82000      | 61000      |
| 200   | 31500      | 27000      |
| 300   | 45000      | NA         |

Because the GEOID's 300 and 400 don't match, the third row results in an NA.

::: {.callout-warning collapse="false"}
Take note! The GEOID's must be the same character type (eg. string)
:::

#### Full Join

```{full_join(income.b, income.c, by="GEOID")}
```

### Geometry

```{get_acs(..., geometry=TRUE)}
```

When you add this option it creates a column in the table with the geometry of the variable. Note that this column is sticky (it is always there), and it can slow down some operations/render some unusable. This is why we learn how to remove it first and add it back again later.

#### Example

| GEOID | med.inc.23 | Geometry                      |
|-------|------------|-------------------------------|
| 100   | 82000      | POLYGON(-75.235345, 39.45332) |
| 200   | 31500      | POLYGON(-75.223445, 39.45643) |
| 300   | 45000      | POLYGON(-75.290755, 40.45332) |

::: callout-tip
Take note on the coordinate system being used in geometry. The important thing to know is the **Coordinate Reference Systems (CRS).**
:::

### CRS

There are two main families of CRS. We have **Geographic** and **Projected.**

| Geographic | Projected |
|----|----|
| These live on a sphere |  |
| Units: Degrees |  |
|  | Good for: Local mapping (example: State Plane - specific to USA). |

::: callout-tip
For State Plane, it halves the state and draws a line of tangency through it before projecting it through a cylindrical projection. Then, this was passed through a coordinate grid system based on measured distance. **Units: Feet OR meters**. However, you need to check which unit of the State Plane you have is using.
:::

::: callout-tip
The earth's shape is a **geoid** (lumpy). However, this is inconvenient for measuring coordinates, so we approximate it to an **ellipsoid** with a flattening ratio. *However, this is a poor fit (because it is an approximation)*. Thus, since the age of exploration, mathematicians and geographers have been attempting to minimize the errors in the fit.
:::

#### Theoretical Steps to Creating a CRS

1.  Flattening and approximating
2.  Choosing a point to fix the ellipse to the earth's surface (in the example of Clark 1866, this was Meades Ranch, KS. This created the North American Datum of 1927 - NAD27)

::: callout-tip
The NAD27 is not used anymore, though you may come across NAD83 which was calibrated via GRS-80 satellites instead. This is earth-centered.
:::

Now, we commonly use WGS84. This is the GPS standard. However, while it is good for navigating, it is not good for geometric calculations. Hence, you generally do not want to use this in GIS. It also distorts the shapes, areas, distance, and direction when we do not project it.

### Map Projections

All projections of the earth start with a 3D model of the earth that is subsequently flattened. Imagine you are holding a paper in the shape of a cylinder. With the earth model in the center, think about shining a light on the bottom and having the lines projected onto the cylinder. This is known as a cylindrical projection (one of the most well-known map projections uses this method: The Mercator projection). The closer the earth model is to the paper, the more accurate it is (no distortion). This is known as the line of tangency.

#### Transverse Cylindrical Projections

These use the cylinder on its side and projects via the longitude.

#### Conic Projections

These are more friendly to the countries in the higher latitudes as it is more accurate there.

#### Planar Projections

Usually best applied on island areas like Australia. They only have one point of tagency.

#### Choosing Projections

| What You Proritize | Projection                           |
|--------------------|--------------------------------------|
| Shapes             | Conformal (Conic for USA and Russia) |
| Area               | Equal-Area                           |
| Distance           | Equal-Distance                       |
| Direction          | (Generally not used in GIS)          |

### Examples of CRS Units in State Planes

| Projection (EPSG) | Name                     | Units             |
|-------------------|--------------------------|-------------------|
| 2272              | PA, Southern State Plane | US Feet OR Meters |
| UTM               |                          |                   |
| 5070              | Albers Equal Area        | Meters            |
| 4326              | WGS-84                   | Degrees           |
| 4269              | NAD-83                   | Degrees           |

::: {callout-tip}
UTM was developed by the military. It lays out the earth (with the top and bottom cut off) and splits it into 60 zones with 6 degrees in each zone.
:::

### Setting and Changing the CRS in R

::: {callout-warning}
All data is going to come with a CRS. The most common problem you may face with this is that the CRS label is not attached to the data.
:::

The code to attach it back is the `St_set.crs()`. If you want to change it to a different CRS, you should use `St_transform()`.

```{st_crs(data) -> # this will tell you what the CRS is currently set to. We do this because we need to know the units.}
st_set_crs() -> # adding the correct label. This is only used to place the label back on.
st_transform() -> # transforms the coordinate reference system to what you want it to be.
```

### Buffers

```{st_buffer(stations, 500) # note that the 500 is in the units of the layer. If 'stations' is in meters, you will get 500 meters. You have to do the maths}
```

## 3. Spatial Analysis Examples

Anything that you do with spatial begins with `st`. It only works with data with a `geometry` column.

### Intersects

```{st_intersects() # returns whether the geometries intersect (true or false)}
st_touches() # the geometries must share a border (so those nested within are not counted)
st_within() # polygons that are inside another one (returns true)
st_filer() # spatial selection of filter based on distance. Only counts polygons fully within 
st_intersection() # shapes change, usually leading to more shapes
st_union() # everything
```

#### Example

```{st_join(stations, tracts)}
st_distance() # returns a matrix with distance between all of the stations and the tracts (for example)
```
