---
title: "Week 2: Getting Ready"
description: "Let's get the ball rolling."
date: 2026-09-04
title-block-banner: images/note-banner.jpg
title-block-banner-color: white
format: html
---

## Review of Last Week

### Questions From the Class

1.  File Management
2.  Coding Anxiety
3.  Git & Workflow

We use R for the statistical analysis, and Quarto is used to run the code and weave the output into the final document.

> **Things to Note**
>
> This is to test the nesting feature on .md

#### What is Markdown?

Markdown is a file format that we will use to write explanations and narrative next. There is a Markdown language guide on Canvas that is common to anything that uses Markdown (.md), including Quarto.

### Quiz Review

1.  What is the relationship between Quarto and R?

> Quarto is a separate package that calls on r to run code and then builds the document around the results.

2.  What is the difference in scope between \_quarto.yml and the YAML header at the top of an individual .qmd file?

> \_quarto.yml adjusts the global theme settings, while the YAML header adjusts the individual header controls.

3.  What does Git do?

> It is a version tracker that runs locally on your computer, watching your folder for changes.

4.  What is the sequence of work?

> Save, Render, Commit, Push

## What We Did

### Looking Into Themes

> For theme changes, global changes are situated in the `_quarto.yml` page.

### Markdown Syntax

> To find out more about Quarto's Markdown Syntax, visit [here](https://quarto.org/docs/authoring/markdown-basics.html). There are many things to explore.[^1]

[^1]: This is a test of an inline note!

::: callout-note
Note that there are five types of callouts, including: `note`, `warning`, `important`, `tip`, and `caution`.
:::

::: callout-tip
## Tip with Title

This is an example of a callout with a title.
:::

::: {.callout-caution collapse="true"}
## Expand To Learn About Collapse

This is an example of a 'folded' caution callout that can be expanded by the user. You can use `collapse="true"` to collapse it by default or `collapse="false"` to make a collapsible callout that is expanded by default.
:::

## Key Concepts

### Things to Know about R

::: callout-tip
## A Note on The Console

The console is temporary. While it computes `r` script just fine, it will disappear once you close the console.
:::

## Objects, Verbs, Census

::: {.callout-tip collapse="false"}
## Breaking Down R Code

`result <- filter(counties, population > 50000) # keep the big ones!`
:::

1.  `result` - this is an `object`
2.  `<-` - this can also be `=`, it is an `assignment arrow`
3.  `filter` - this is a `function`
4.  `counties` - this is `input data`
5.  `population > 50000` - this is an `argument`

::: {.callout-tip collapse="false"}
## Packages

Packages are things that can be installed and called upon when you are running your code
:::

1.  `install.packages("dplyr")` - this only needs to be done once
2.  `library(dplyr)` - this is like a book. You need to run this every time you use `r`

### Data Frames

| Name | Income | MOE |
|:-----|:-------|:----|
| 12   | 12     | 12  |
| 123  | 123    | 123 |
| 1    | 1      | 1   |

1.  Note: `tibble` is nicer and prints prettier
2.  Note\[2\]: MOE stands for Margin of Error

### Verbs

1.  `filter()` - picks `Rows`
2.  `select()` - picks `Columns`
3.  `mutate()` - adds a new `Computed Column`
4.  `arrange()` - change order of rows in ascending or descending order
5.  `group_by() + summarize()` - many rows become few. For example, for a dataframe with many states and income levels, it can group it by `state` and it can summarize the income levels.

### Manipulating the Data (Example - Novice)

::: {.callout-tip collapse="false"}
## Step 1

`filler(counties, moe_pct >10)`
:::

::: {.callout-tip collapse="false"}
## Step 2

`arrange(Step1, desc(moe_pct))`
:::

::: {.callout-tip collapse="false"}
## Step 3

`Select(Step2,NAME, (moe_pct)`
:::

> However, this is a very novice way of doing things because it creates more unnecessary data frames that pollute your workspace

### Thinking of Advanced Ways

::: {.callout-tip collapse="false"}
While it is good to think about the step-by-step process to be clear about how you are manipulating the data, you can start using the % code to string together functions to compute your data output without creating the files in between.
:::

#### For Example

```         
New__Data <- Counties %>% 
  filter(moe_pct > 10) %>% 
  arrange(desc(moe_pct)) %>%
  Select(NAME, moepct)
```

::: callout-warning
Take note that everything is case sensitive in R. A good rule of thumb is to put everything in lowercase.
:::

### The Census

::: {.callout-tip collapse="false"}
## The Census

The census is a great source of data that we will use. It is mandated by the constitution to count the number of people that live there on an interval of every 10 years (Decennial Census, created by James Madison). Every person that is in the US (legally or illegally) is asked 10 questions on a 10 year basis.
:::

::: {.callout-tip collapse="false"}
## American Community Survey (ACS)

Created in 2005. It replaced the long form of the Decennial Census. It has more data that we are interested in (things like income, travel patterns). Roughly 3% of households are surveyed. From the sample, an estimate for the population is derived. There are two versions of the ACS. 1. The 1-year ACS: Only for places with \>65,000 people (metropolitan level). While it is the most current, we don't often use it in our analysis because we don't often get the neighborhood level. 2. The 3-year ACS (now deprecated): not in use 3. The 5-year ACS: Goes down to block group, census tract...etc. This means that when you get ACS data for the year 2016 (for example), you are accessing the 5-year average of the neighborhood.
:::

## Reflection
