project:
  type: website
  output-dir: docs
  execute-dir: project

website:
  title: "Isaac Tan - MUSA 5080 Portfolio"        # <-- CHANGE THIS
  description: "Public Policy Analytics portfolio"
  navbar:
    title: "Portfolio"
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: weekly-notes/index.qmd
        text: "Weekly Notes"
      - href: assignments/index.qmd
        text: "Assignments"
    right:
      - icon: envelope-fill
        href: mailto:isaactan@upenn.edu
      - icon: linkedin
        href: https://www.linkedin.com/in/isaactanjy
      - icon: github
        href: https://github.com/isaactanjy/MUSA-5080-portfolio
  page-footer:
    left: "Copyright 2026, Isaac Tan"
    right:
      - icon: envelope-fill
        href: mailto:isaactan@upenn.edu
      - icon: linkedin
        href: https://www.linkedin.com/in/isaactanjy
      - icon: github
        href: https://github.com/isaactanjy/MUSA-5080-portfolio



format:
  html:
    css: /styles.css
    theme:
      light: cosmo
      dark: [solar, theme-dark.scss]
    respect-user-color-scheme: true
    toc: true
    code-fold: false
    code-tools: true
    title-block-banner: images/banner.jpg
    title-block-banner-color: "white"


execute:
  freeze: auto
  echo: true
  warning: false
  message: false
