{
  "hash": "80a4107b37ee96489058cb4ebfcf3765",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Assignment 2: Who Do We Know the Least About?\"\nsubtitle: \"Measuring uncertainty in American Community Survey data\"\nauthor: \"Isaac Tan\"\ndate: today\nformat:\n  html:\n    toc: true\n    code-fold: false\nexecute:\n  warning: false\n  message: false\neditor: \n  markdown: \n    wrap: 72\n---\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidycensus)\n```\n:::\n\n\n------------------------------------------------------------------------\n\n## The question\n\nEvery number the American Community Survey publishes is an estimate\ndrawn from a sample, not a count. That means every number comes with a\nmargin of error — a statement about how wrong it might be.\n\nMost people ignore it. In this assignment, you won't.\n\n**In this analysis, I look at Median Home Value across counties in\nIllinois, and ask which communities we measure most and least\nreliably.**\n\n------------------------------------------------------------------------\n\n## Choosing what to measure\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_state <- \"IL\"        # two-letter abbreviation, in quotes\nmy_variable <- \"B25077_001\"     # the variable code, in quotes\n```\n:::\n\n\n## Pulling the data\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- get_acs(\n  geography = \"county\",\n  variables = my_variable,\n  state = my_state,\n  year = 2023,\n  survey = \"acs5\"\n)\n```\n:::\n\n\nLet's look at what came back.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(county_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 102   5\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(county_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  GEOID NAME                       variable   estimate   moe\n  <chr> <chr>                      <chr>         <dbl> <dbl>\n1 17001 Adams County, Illinois     B25077_001   155900  4554\n2 17003 Alexander County, Illinois B25077_001    58700 10578\n3 17005 Bond County, Illinois      B25077_001   133100 13683\n4 17007 Boone County, Illinois     B25077_001   198600  8350\n5 17009 Brown County, Illinois     B25077_001   142200 19435\n6 17011 Bureau County, Illinois    B25077_001   121900  3733\n```\n\n\n:::\n:::\n\n\n**The function returned 102 rows, which matches the number of counties\nwithin Illinois**\n\n------------------------------------------------------------------------\n\n## How big is the margin of error?\n\nA margin of error of 3,000 means something very different for an\nestimate of 20,000 than for an estimate of 200,000. To compare across\nplaces, we need it as a percentage.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- county_data %>%\n  mutate(moe_pct = moe / estimate * 100)\n```\n:::\n\n\nNow sort to see which counties are measured least reliably.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data %>%\n  arrange(desc(moe_pct)) %>%\n  select(NAME, estimate, moe, moe_pct) %>%\n  head(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 4\n   NAME                       estimate   moe moe_pct\n   <chr>                         <dbl> <dbl>   <dbl>\n 1 Hardin County, Illinois       91700 31269    34.1\n 2 Alexander County, Illinois    58700 10578    18.0\n 3 Jasper County, Illinois      122900 17070    13.9\n 4 Hamilton County, Illinois    108800 15103    13.9\n 5 Brown County, Illinois       142200 19435    13.7\n 6 Calhoun County, Illinois     174000 21433    12.3\n 7 Pulaski County, Illinois      81000  9539    11.8\n 8 Massac County, Illinois      118000 13228    11.2\n 9 Scott County, Illinois       101700 11145    11.0\n10 Bond County, Illinois        133100 13683    10.3\n```\n\n\n:::\n:::\n\n\n**Hardin County is the county with the largest margin of error relative\nto its estimate at 34.09924.**\n\n------------------------------------------------------------------------\n\n## Sorting counties into reliability categories\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- county_data %>%\n  mutate(reliability = case_when(\n    moe_pct < 5  ~ \"High confidence\",\n    moe_pct < 10 ~ \"Moderate\",\n    TRUE         ~ \"Low confidence\"\n  ))\n\ncount(county_data, reliability)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  reliability         n\n  <chr>           <int>\n1 High confidence    49\n2 Low confidence     11\n3 Moderate           42\n```\n\n\n:::\n:::\n\n\n**From the calculations, 49 counties fall under 'High Confidence', 42\ncounties fall under 'Moderate', and 11 counties fall under 'Low\nConfidence'.**\n\n------------------------------------------------------------------------\n\n## Is the margin of error bigger in small places?\n\nTo answer this we need population and our variable side by side, in the\nsame row. That means a **wide** pull.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide <- get_acs(\n  geography = \"county\",\n  variables = c(myvar = my_variable,\n                pop   = \"B01003_001\"),\n  state = my_state,\n  year = 2023,\n  survey = \"acs5\",\n  output = \"wide\"\n)\n\nhead(county_wide)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 6\n  GEOID NAME                       myvarE myvarM  popE  popM\n  <chr> <chr>                       <dbl>  <dbl> <dbl> <dbl>\n1 17001 Adams County, Illinois     155900   4554 65166    NA\n2 17003 Alexander County, Illinois  58700  10578  5042    NA\n3 17005 Bond County, Illinois      133100  13683 16627    NA\n4 17007 Boone County, Illinois     198600   8350 53316    NA\n5 17009 Brown County, Illinois     142200  19435  6320    NA\n6 17011 Bureau County, Illinois    121900   3733 33027    NA\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide <- county_wide %>%\n  mutate(moe_pct = myvarM / myvarE * 100) %>%\n  mutate(reliability = case_when(\n    moe_pct < 5  ~ \"High confidence\",\n    moe_pct < 10 ~ \"Moderate\",\n    TRUE         ~ \"Low confidence\"\n  ))\n```\n:::\n\n\nNow compare the average population of counties in each reliability\ncategory.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide %>%\n  group_by(reliability) %>%\n  summarize(\n    n_counties = n(),\n    avg_population = mean(popE)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  reliability     n_counties avg_population\n  <chr>                <int>          <dbl>\n1 High confidence         49        240766.\n2 Low confidence          11          7351.\n3 Moderate                42         19387 \n```\n\n\n:::\n:::\n\n\n**This table illustrates a pattern between average population and the\nlevel of confidence we have in the Median Home Value estimates. The\naverage population of counties with high confidence was 240,766.12,\nwhile the average population of counties with low confidence was\n7350.818. Counties with moderate levels of confidence had an average\npopulation of 19,387. The pattern is generally that with higher\npopulations, the level of confidence in the data increases.**\n\n------------------------------------------------------------------------\n\n## What this means for policy\n\n1.  *We\n    know the least about the 11 counties with the lowest confidence\n    levels. This would be Pope County, Bond County, Scott County, Massac\n    County, Pulaski County, Calhoun County, Brown County, Hamilton\n    County, Jasper County, Alexander County, and Hardin County, which\n    had a margin of error percent range of 10.275 to 34.099. As seen in\n    the above table, these counties also have lower average populations\n    compared to the rest of the state.*\n2.  *As the ACS5\n    already measures a slice of the county population, smaller counties\n    like Hardin County (with about a population of 3623) will have\n    smaller samples that lead to higher variability in the median. With\n    a small population, the statistical standard error increases,\n    resulting in imprecision within the data. Hence, we can conclude\n    that the states with the lower populations are the communities that\n    we know the least about from the ACS5 data.*\n3.  *If a state agency\n    allocates funding using the variable of median home values, there is\n    a high probability that the ACS5 estimate of the true median of a\n    county may be higher than the actual value. This error in the\n    estimate may result in low confidence counties appearing wealthier\n    than they actually are and receiving less aid than they would need,\n    thus resulting in an inequitable provision of welfare funding.*\n\n\n\n",
    "supporting": [
      "assignment2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}